name       : owncloud-client
version    : 2.4.2
release    : 22
source     :
    - https://github.com/owncloud/client/archive/v2.4.2.tar.gz : 2b5b3f0da9e467e8d73e85aec0aea9c98f6c353b36f0306389ece5ce793a38f4
license    : GPL-2.0
component  : network.download
summary    : The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer
description: |
    The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    - qtkeychain-devel
    - xdg-utils
rundeps    :
    - libgnome-keyring
libsplit   : no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    sed -i 's/Utility;X-SuSE-SyncUtility;/Network;/g' $installdir/usr/share/applications/owncloud.desktop

