name       : owncloud-client
version    : 2.2.2
release    : 8
source     :
    - https://download.owncloud.com/desktop/stable/owncloudclient-2.2.2.tar.xz : 368109ab0cf85b3b286d1479e5e585f6cdb70647d0a51afbc3581c2ec2ee1754
license    : GPL-2.0
component  : network.download
summary    : The ownCloud Desktop Client is a tool to synchronize files from ownCloud
    Server with your computer.
description: |
    The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(python-2.7)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    - qtkeychain-devel
    - xdg-utils
libsplit   : no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
