name       : owncloud-client
version    : 2.8.2.4246
release    : 32
source     :
    - https://download.owncloud.com/desktop/ownCloud/stable/2.8.2.4246/source/ownCloud-2.8.2.4246.tar.xz : 0cc2e5154a1349bd21941ac3c32e8621778a9ff150730a19de2710e22d32fc43
license    : GPL-2.0-or-later
component  : network.download
summary    : The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer
description: |
    The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(cloudproviders)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - qtkeychain-devel
    - shared-mime-info
    - xdg-utils
rundeps    :
    - libgnome-keyring
libsplit   : no
setup      : |
    %patch -p1 < $pkgfiles/fix-build-glib2.patch
    %patch -p1 < $pkgfiles/Fix-use-of-deleted-function.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
    sed -i 's/Utility;X-SuSE-SyncUtility;/Network;/g' $installdir/usr/share/applications/owncloud.desktop
