name       : owncloud-client
version    : 2.2.1
release    : 5
source     :
    - https://download.owncloud.com/desktop/stable/owncloudclient-2.2.1.tar.xz : 70d464dcf3f67d6377fdcae755c5dd26de539c323e0d5f445e957832a5303af2
license    : GPL-2.0
component  : desktop.qt
summary    : The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
description: |
    The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(python-2.7)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    - qtkeychain-devel
    - xdg-utils
libsplit   : no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
