name       : owncloud-client
version    : 2.1.1
release    : 3
source     :
    - https://download.owncloud.com/desktop/stable/owncloudclient-2.1.1.tar.xz : 4e7cfeb72ec565392e7968f352c4a7f0ef2988cc577ebdfd668a3887d320b1cb
license    : GPL-2.0
summary    : The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
description: |
    The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(python-2.7)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    - qtkeychain-devel
    - xdg-utils
libsplit: no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
