name       : owncloud-client
version    : 2.6.1
release    : 28
source     :
    - git|https://github.com/owncloud/client.git : v2.6.1
license    : GPL-2.0-or-later
component  : network.download
summary    : The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer
description: |
    The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(cloudproviders)
    - pkgconfig(egl)
    - pkgconfig(sqlite3)
    - qtkeychain-devel
    - shared-mime-info
    - xdg-utils
rundeps    :
    - libgnome-keyring
libsplit   : no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    sed -i 's/Utility;X-SuSE-SyncUtility;/Network;/g' $installdir/usr/share/applications/owncloud.desktop
