name       : owncloud-client
version    : 2.3.3
release    : 17
source     :
    - https://github.com/owncloud/client/archive/v2.3.3.tar.gz : 6f37de32ad3992fe3f7a6c2ff5675612506cf768e945a2568a9c105773246d77
license    : GPL-2.0
component  : network.download
summary    : The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
description: |
    The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(python-2.7)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    - qtkeychain-devel
    - xdg-utils
rundeps    :
    - libgnome-keyring
libsplit   : no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    sed -i 's/Utility;X-SuSE-SyncUtility;/Network;/g' $installdir/usr/share/applications/owncloud.desktop
