name       : owncloud-client
version    : 2.5.2
release    : 25
source     :
    - https://github.com/owncloud/client/archive/v2.5.2.tar.gz : 5210e0d69b7e89daea3cf1dda37986d827614bf1e4d369a4e9efdf4aeff34548
license    : GPL-2.0-or-later
component  : network.download
summary    : The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer
description: |
    The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(egl)
    - pkgconfig(sqlite3)
    - qtkeychain-devel
    - xdg-utils
rundeps    :
    - libgnome-keyring
libsplit   : no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    sed -i 's/Utility;X-SuSE-SyncUtility;/Network;/g' $installdir/usr/share/applications/owncloud.desktop
