name       : owncloud-client
version    : 2.3.2
release    : 16
source     :
    - https://github.com/owncloud/client/archive/v2.3.2.tar.gz : 4daddcc3c90d7cba038aa509d6bf9eae09505fb48ca55937e135de19e4d8e2c4
license    : GPL-2.0
component  : network.download
summary    : The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
description: |
    The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(python-2.7)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    - qtkeychain-devel
    - xdg-utils
rundeps    :
    - libgnome-keyring
libsplit   : no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    sed -i 's/Utility;X-SuSE-SyncUtility;/Network;/g' $installdir/usr/share/applications/owncloud.desktop
