name       : owncloud-client
version    : 2.0.2
release    : 1
source     :
    - https://download.owncloud.com/desktop/stable/owncloudclient-2.0.2.tar.xz : 2815dce34b568141d7c2ab90bcd733abb6862970917738e3b120d8073ab68228
license    : GPL-2.0
summary    : The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
description: |
    The ownCloud Desktop Client is a tool to synchronize files from ownCloud Server with your computer.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(python-2.7)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    - qtkeychain-devel
    - xdg-utils
libsplit: no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
